# Generated by Django 5.2.3 on 2025-06-22 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id_capteur', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom_capteur', models.CharField(max_length=50, unique=True)),
                ('piece', models.CharField(max_length=50)),
                ('emplacement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capteurs.capteur')),
            ],
        ),
    ]
